from token import Token

INTEGER, REAL, EOF = 'INTEGER', 'REAL', 'EOF'
INTEGER_CONST, REAL_CONST = 'INTEGER_CONST', 'REAL_CONST'

PLUS, MINUS, MUL = 'PLUS', 'MINUS', 'MUL'
INTEGER_DIV, FLOAT_DIV = 'INTEGER_DIV', 'FLOAT_DIV'

LPAREN, RPAREN = '(', ')'
ASSIGN, SEMI, DOT = ':=', ';', 'DOT'

PROGRAM, VAR, BEGIN, END, ID = 'PROGRAM', 'VAR', 'BEGIN', 'END', 'ID'
COLON, COMMA = 'COLON', 'COMMA'

RESERVED_KEYWORDS = {
    'PROGRAM': Token('PROGRAM', 'PROGRAM'),
    'VAR': Token('VAR', 'VAR'),
    'DIV': Token('INTEGER_DIV', 'DIV'),
    'INTEGER': Token('INTEGER', 'INTEGER'),
    'REAL': Token('REAL', 'REAL'),
    'BEGIN': Token('BEGIN', 'BEGIN'),
    'END': Token('END', 'END'),
}
